// Landing Page
import Link from "next/link";
import { ArrowRight, BarChart3, Bot, Leaf, Shield, Zap } from "lucide-react";
import { Button, buttonVariants } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

export default function Home() {
  return (
    <div className="flex flex-col w-full">
      {/* Hero Section */}
      <section className="relative overflow-hidden pt-24 pb-32 lg:pt-36 lg:pb-40">
        <div className="absolute inset-0 bg-gradient-to-b from-primary/5 via-background to-background z-0" />
        <div className="absolute -top-[500px] -right-[500px] w-[1000px] h-[1000px] rounded-full bg-primary/5 blur-3xl opacity-50 z-0" />
        
        <div className="container mx-auto px-4 md:px-8 relative z-10 flex flex-col items-center text-center">
          <Badge variant="secondary" className="mb-8 px-4 py-1.5 text-sm rounded-full bg-primary/10 text-primary hover:bg-primary/20 border-primary/20">
            ✨ Introducing CarbonCoach AI
          </Badge>
          
          <h1 className="text-5xl md:text-7xl font-extrabold tracking-tight max-w-4xl mb-8 leading-[1.1]">
            Understand & Reduce Your <span className="text-transparent bg-clip-text bg-gradient-to-r from-emerald-500 to-primary">Carbon Footprint</span>
          </h1>
          
          <p className="text-xl md:text-2xl text-muted-foreground max-w-2xl mb-12 leading-relaxed">
            AI-powered insights, deterministic tracking, and intelligent simulations to help you make sustainable choices effortlessly.
          </p>
          
          <div className="flex flex-col sm:flex-row gap-4 w-full sm:w-auto">
            <Link href="/signup" className={cn(buttonVariants({ size: "lg" }), "w-full sm:w-auto h-14 px-8 text-base rounded-full shadow-xl shadow-primary/20 hover:shadow-primary/40 transition-all gap-2 group")}>
              Start Your Assessment
              <ArrowRight className="h-4 w-4 group-hover:translate-x-1 transition-transform" />
            </Link>
            <Link href="#features" className={cn(buttonVariants({ size: "lg", variant: "outline" }), "w-full sm:w-auto h-14 px-8 text-base rounded-full bg-background/50 backdrop-blur")}>
              Explore Features
            </Link>
          </div>
        </div>
      </section>

      {/* Features Grid */}
      <section id="features" className="py-24 bg-muted/30">
        <div className="container mx-auto px-4 md:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold mb-4">Powerful tools for a sustainable life</h2>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
              Everything you need to measure, understand, and reduce your environmental impact.
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8 max-w-6xl mx-auto">
            <FeatureCard 
              icon={<BarChart3 className="h-6 w-6 text-emerald-500" />}
              title="Deterministic Engine"
              description="Accurate, reliable carbon calculations based on established scientific emission factors. No AI hallucinations."
            />
            <FeatureCard 
              icon={<Bot className="h-6 w-6 text-blue-500" />}
              title="AI Recommendations"
              description="Personalized, actionable insights generated by Google Gemini to help you reduce your footprint."
            />
            <FeatureCard 
              icon={<Zap className="h-6 w-6 text-amber-500" />}
              title="What-If Simulations"
              description="Interactive sliders let you simulate the impact of lifestyle changes before you make them."
            />
            <FeatureCard 
              icon={<Leaf className="h-6 w-6 text-green-500" />}
              title="Carbon Twin"
              description="Relatable comparisons—understand your impact in terms of trees, flights, or everyday items."
            />
            <FeatureCard 
              icon={<Shield className="h-6 w-6 text-indigo-500" />}
              title="Privacy First"
              description="Your data is secure. We use enterprise-grade encryption and strict privacy controls."
            />
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-32 relative overflow-hidden">
        <div className="absolute inset-0 bg-primary/5 z-0" />
        <div className="container mx-auto px-4 md:px-8 relative z-10 text-center">
          <h2 className="text-4xl font-bold mb-6">Ready to make a difference?</h2>
          <p className="text-xl text-muted-foreground mb-10 max-w-2xl mx-auto">
            Join thousands of others taking steps towards a greener future. It takes less than 3 minutes.
          </p>
          <Link href="/signup" className={cn(buttonVariants({ size: "lg" }), "h-14 px-10 text-base rounded-full shadow-lg hover:scale-105 transition-all duration-300")}>
            Create Free Account
          </Link>
        </div>
      </section>
    </div>
  );
}

function FeatureCard({ icon, title, description }: { icon: React.ReactNode, title: string, description: string }) {
  return (
    <Card className="border-none shadow-md hover:shadow-xl transition-all duration-300 bg-background/60 backdrop-blur group">
      <CardContent className="p-8">
        <div className="mb-6 p-4 bg-muted rounded-2xl w-fit group-hover:scale-110 transition-transform duration-300">
          {icon}
        </div>
        <h3 className="text-xl font-bold mb-3">{title}</h3>
        <p className="text-muted-foreground leading-relaxed">{description}</p>
      </CardContent>
    </Card>
  );
}
